// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

#include "duckdb_static_extensions.h"

#include <mutex>
#include <string>

#if GIZMOSQL_DUCKDB_MAJOR_VERSION >= 2
#include <duckdb_static_extension.h>

// Defined in each extension archive (generated by DuckDB's
// duckdb_add_extension_describe). Naming them here is also what pulls the
// archives' members into the link: an archive that is missing fails the link
// instead of the extension vanishing at runtime.
extern "C" {
int32_t duckdb_extension_core_functions_describe(duckdb_extension_descriptor* descriptor);
int32_t duckdb_extension_parquet_describe(duckdb_extension_descriptor* descriptor);
int32_t duckdb_extension_icu_describe(duckdb_extension_descriptor* descriptor);
int32_t duckdb_extension_tpch_describe(duckdb_extension_descriptor* descriptor);
#if defined(GIZMOSQL_IOS_STATIC_EXTENSIONS)
int32_t duckdb_extension_ducklake_describe(duckdb_extension_descriptor* descriptor);
int32_t duckdb_extension_httpfs_describe(duckdb_extension_descriptor* descriptor);
int32_t duckdb_extension_postgres_scanner_describe(duckdb_extension_descriptor* descriptor);
#endif
}
#endif

namespace gizmosql::ddb {

arrow::Status RegisterStaticExtensions() {
#if GIZMOSQL_DUCKDB_MAJOR_VERSION >= 2
  static std::once_flag once;
  static arrow::Status result;
  std::call_once(once, [] {
    struct NamedDescribe {
      const char* name;
      duckdb_extension_describe_t describe;
    };
    const NamedDescribe extensions[] = {
        {"core_functions", duckdb_extension_core_functions_describe},
        {"parquet", duckdb_extension_parquet_describe},
        {"icu", duckdb_extension_icu_describe},
        {"tpch", duckdb_extension_tpch_describe},
#if defined(GIZMOSQL_IOS_STATIC_EXTENSIONS)
        {"ducklake", duckdb_extension_ducklake_describe},
        {"httpfs", duckdb_extension_httpfs_describe},
        {"postgres_scanner", duckdb_extension_postgres_scanner_describe},
#endif
    };
    for (const auto& extension : extensions) {
      if (duckdb_register_static_extension(extension.describe) != 0) {
        result = arrow::Status::Invalid("Failed to register statically linked DuckDB "
                                        "extension '",
                                        extension.name, "'");
        return;
      }
    }
  });
  return result;
#else
  return arrow::Status::OK();
#endif
}

}  // namespace gizmosql::ddb
