apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: gizmosql
spec:
  selector:
    matchLabels:
      app: gizmosql
      gizmosql-metrics: enabled
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 15s
